language: node_js
node_js:
  - 0.10
services:
  - mongodb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/example.json config/development.json
  - npm start > /dev/null &
  - npm run update-webdriver
  - curl -O https://pithos.grnet.gr/pithos/rest/skanct@grnet-hq.admin.grnet.gr/files/selenium-server-standalone-2.41.0.jar
  - mv selenium-server-standalone-2.41.0.jar /tmp/
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/karma start test/ang/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor test/ang/protractor-conf.js --browser=firefox
